version: "3.8"

services:

  localstack:
    image: localstack/localstack:2.3
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
      - AWS_DEFAULT_REGION=us-east-1

  api:
    build: ./api-service
    container_name: api-service
    ports:
      - "5000:5000"
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://host.docker.internal:4566
      S3_BUCKET_RAW: raw-images-propelhq
      S3_BUCKET_PROCESSED: processed-images-propelhq
      SQS_QUEUE_URL: http://host.docker.internal:4566/000000000000/image-processing-queue-propelhq
    depends_on:
      - localstack
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    build: ./worker-service
    container_name: worker-service
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://host.docker.internal:4566
      S3_BUCKET_RAW: raw-images-propelhq
      S3_BUCKET_PROCESSED: processed-images-propelhq
      SQS_QUEUE_URL: http://host.docker.internal:4566/000000000000/image-processing-queue-propelhq
    depends_on:
      - localstack
    extra_hosts:
      - "host.docker.internal:host-gateway"