name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: |
          cd api-service
          pip install -r src/requirements.txt pytest pytest-mock
          pytest tests -v

      - run: |
          cd worker-service
          pip install -r src/requirements.txt pytest pytest-mock pillow
          pytest tests -v


  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests pytest pillow boto3 awscli-local

      - run: docker compose up -d --build

      - run: |
          for i in {1..20}; do
            if curl -s http://localhost:4566/_localstack/health | grep -q '"initialized": true'; then
              break
            fi
            sleep 3
          done

      - run: |
          awslocal s3 mb s3://raw-images-propelhq || true
          awslocal s3 mb s3://processed-images-propelhq || true
          awslocal sqs create-queue --queue-name image-processing-queue-propelhq || true

      - run: |
          for i in {1..15}; do
            if curl -s http://localhost:5000/health | grep -q "ok"; then
              break
            fi
            sleep 3
          done

      - run: pytest tests/integration --integration -v
        env:
          AWS_ENDPOINT_URL: http://localstack:4566
          S3_BUCKET_RAW: raw-images-propelhq
          S3_BUCKET_PROCESSED: processed-images-propelhq
          SQS_QUEUE_URL: http://localstack:4566/000000000000/image-processing-queue-propelhq


  build:
    runs-on: ubuntu-latest
    needs: integration-tests

    steps:
      - uses: actions/checkout@v4
      - run: docker build -t propelhq-api ./api-service
      - run: docker build -t propelhq-worker ./worker-service


  push:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/propelhq-api ./api-service
          docker push ${{ secrets.DOCKER_USERNAME }}/propelhq-api

      - run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/propelhq-worker ./worker-service
          docker push ${{ secrets.DOCKER_USERNAME }}/propelhq-worker
